# Generated by Django 2.0.2 on 2018-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologia', '0002_auto_20180509_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
