# Generated by Django 2.0.2 on 2018-05-12 16:34

from django.db import migrations, models
import django.utils.timezone
import ontologia.models
import ontologia.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ontologia', '0003_fichier_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier',
            old_name='thematic',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='fichier',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='fichier',
            name='thematiques',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichier',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=ontologia.models.upload_location, validators=[ontologia.validators.validate_file_extension]),
        ),
    ]
