# Generated by Django 2.0.2 on 2018-05-15 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ontologia', '0004_auto_20180512_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='categorie',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
