# Generated by Django 2.0.2 on 2018-06-01 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ontologia', '0005_fichier_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='etiquettes',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
